"""initial schema

Revision ID: 41245f4f9313
Revises: 
Create Date: 2026-03-12 04:56:35.162197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41245f4f9313'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.Enum('free', 'starter', 'pro', 'enterprise', name='plan_type'), server_default='free', nullable=False),
    sa.Column('monthly_budget_limit', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('daily_budget_limit', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('circuit_breaker_enabled', sa.Boolean(), nullable=False),
    sa.Column('circuit_breaker_threshold', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('circuit_breaker_window_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('providers',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('alert_rules',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('budget_soft', 'budget_hard', 'anomaly', 'circuit_breaker', name='alert_rule_type'), nullable=False),
    sa.Column('scope', sa.Enum('hourly', 'daily', 'monthly', name='alert_scope'), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('anomaly_multiplier', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_organization_id'), 'alert_rules', ['organization_id'], unique=False)
    op.create_table('models',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('cost_per_1m_input_tokens', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('cost_per_1m_output_tokens', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('category', sa.Enum('flagship', 'mid', 'economy', name='model_category'), nullable=False),
    sa.Column('supports_vision', sa.Boolean(), nullable=False),
    sa.Column('supports_code', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pricing_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_provider_id'), 'models', ['provider_id'], unique=False)
    op.create_table('notification_channels',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('slack', 'email', 'sms', name='notification_channel_type'), nullable=False),
    sa.Column('config_encrypted', sa.String(length=2000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_channels_organization_id'), 'notification_channels', ['organization_id'], unique=False)
    op.create_table('provider_api_keys',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('openai', 'anthropic', 'google', 'mistral', name='provider_name'), nullable=False),
    sa.Column('key_ciphertext', sa.String(length=1000), nullable=False),
    sa.Column('key_prefix', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_api_keys_organization_id'), 'provider_api_keys', ['organization_id'], unique=False)
    op.create_table('service_api_keys',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_service_api_keys_organization_id'), 'service_api_keys', ['organization_id'], unique=False)
    op.create_table('tags',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_organization_id'), 'tags', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'viewer', name='user_role'), server_default='viewer', nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret_encrypted', sa.String(length=500), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('alert_events',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('alert_rule_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='alert_severity'), nullable=False),
    sa.Column('type', sa.Enum('soft_limit', 'hard_limit', 'anomaly', 'circuit_breaker', name='alert_event_type'), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('triggered_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('notification_channels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_organization_id'), 'alert_events', ['organization_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('key_created', 'key_revoked', 'login', 'login_failed', 'logout', 'budget_changed', 'circuit_breaker_triggered', 'circuit_breaker_released', 'member_invited', name='audit_action'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('model_benchmarks',
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.Enum('code', 'vision', 'chat', 'summary', 'classification', 'rag', name='task_type'), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('quality_source', sa.Enum('public_benchmark', 'shadow_test', 'client_feedback', name='quality_source'), nullable=False),
    sa.Column('avg_latency_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('recommendation', sa.Enum('best_value', 'premium', 'economy', 'overkill', name='benchmark_recommendation'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_benchmarks_model_id'), 'model_benchmarks', ['model_id'], unique=False)
    op.create_table('optimization_suggestions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('current_model_id', sa.UUID(), nullable=False),
    sa.Column('suggested_model_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.Enum('code', 'vision', 'chat', 'summary', 'classification', 'rag', name='task_type'), nullable=False),
    sa.Column('affected_requests_count', sa.Integer(), nullable=False),
    sa.Column('current_monthly_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('projected_monthly_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('estimated_savings', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('quality_current', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('quality_suggested', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'dismissed', name='suggestion_status'), server_default='pending', nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['suggested_model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_suggestions_organization_id'), 'optimization_suggestions', ['organization_id'], unique=False)
    op.create_table('shadow_test_results',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('original_model_id', sa.UUID(), nullable=False),
    sa.Column('test_model_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.Enum('code', 'vision', 'chat', 'summary', 'classification', 'rag', name='task_type'), nullable=False),
    sa.Column('similarity_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('cost_original', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('cost_test', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('latency_original_ms', sa.Integer(), nullable=False),
    sa.Column('latency_test_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['original_model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['test_model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shadow_test_results_organization_id'), 'shadow_test_results', ['organization_id'], unique=False)
    op.create_table('usage_logs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('service_api_key_id', sa.UUID(), nullable=True),
    sa.Column('provider_api_key_id', sa.UUID(), nullable=True),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.Enum('code', 'vision', 'chat', 'summary', 'classification', 'rag', name='task_type'), server_default='chat', nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('is_streaming', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['provider_api_key_id'], ['provider_api_keys.id'], ),
    sa.ForeignKeyConstraint(['service_api_key_id'], ['service_api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_logs_created_at'), 'usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_logs_model_id'), 'usage_logs', ['model_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_organization_id'), 'usage_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_provider_api_key_id'), 'usage_logs', ['provider_api_key_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_service_api_key_id'), 'usage_logs', ['service_api_key_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_logs_service_api_key_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_provider_api_key_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_organization_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_model_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_created_at'), table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_index(op.f('ix_shadow_test_results_organization_id'), table_name='shadow_test_results')
    op.drop_table('shadow_test_results')
    op.drop_index(op.f('ix_optimization_suggestions_organization_id'), table_name='optimization_suggestions')
    op.drop_table('optimization_suggestions')
    op.drop_index(op.f('ix_model_benchmarks_model_id'), table_name='model_benchmarks')
    op.drop_table('model_benchmarks')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alert_events_organization_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_organization_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_service_api_keys_organization_id'), table_name='service_api_keys')
    op.drop_table('service_api_keys')
    op.drop_index(op.f('ix_provider_api_keys_organization_id'), table_name='provider_api_keys')
    op.drop_table('provider_api_keys')
    op.drop_index(op.f('ix_notification_channels_organization_id'), table_name='notification_channels')
    op.drop_table('notification_channels')
    op.drop_index(op.f('ix_models_provider_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_alert_rules_organization_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_table('providers')
    op.drop_table('organizations')
    # ### end Alembic commands ###
